services:
  ollama:
    image: ollama/ollama
    restart: unless-stopped
    container_name: ollama
    environment:
      OLLAMA_CONTEXT_LENGTH: 131072
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - kanban-net

networks:
  kanban-net:
    external: true

volumes:
  ollama_data:
