[project]
name = "ollama-chat"
version = "0.1.0"
description = "Simple, terminal-based chat interface for the Ollama provider"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ollama>=0.6.0",
    "textual>=6.1.0",
]
