load("@rules_python//python:defs.bzl", "py_library")

package(
    default_visibility = ["//pybazel:visibility"],
)

py_library(
    name = "info",
    srcs = ["info.py"],
)

py_library(
    name = "label",
    srcs = ["label.py"],
)
