[[task]]
label = "Backend"
container_port = 8080

[[task]]
label = "Frontend"
container_port = 5173

[[task]]
label = "Frontend (Local Backend)"
container_port = 5174

[[task]]
label = "Docs"
container_port = 5175

[sync]
allow_rebase = true
allow_merge = false

[merge]
allow_merge_commit = false
allow_squash = true
allow_rebase = false
