apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: navidrome-music
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
