apiVersion: v1
kind: Service
metadata:
  name: navidrome
spec:
  type: NodePort
  ports:
    - name: "4533"
      port: 4533
      targetPort: 4533
      nodePort: 30533
  selector:
    app: navidrome
