py_library(
    name = "queue",
    srcs = ["queue.py"],
)

py_test(
    name = "queue_test",
    srcs = ["queue_test.py"],
    deps = [":queue"],
)

py_library(
    name = "stack",
    srcs = ["stack.py"],
)

py_test(
    name = "stack_test",
    srcs = ["stack_test.py"],
    deps = [":stack"],
)
