name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: Install deps
        run: >-
          python -m pip install --upgrade pip &&
          pip install twine==4.0.0 build==0.9.0
      - name: Build
        run: python -m build
      - name: Upload
        run: twine upload dist/*.tar.gz
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
