services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf
    container_name: audiobookshelf
    expose:
      - 80
    volumes:
      - ./config:/config
      - ./metadata:/metadata
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/:/etc/nginx/:ro
    depends_on:
      - audiobookshelf
      - buildbuddy
      - docker-status
      - pihole
      - proxpi
      - pacoloco
      - glances

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  buildbuddy:
    image: gcr.io/flame-public/buildbuddy-app-onprem
    container_name: buildbuddy
    restart: unless-stopped
    expose:
      - 1985
      - 8080
    ports:
      - "1985:1985"
    volumes:
      - buildbuddy_data:/var/lib/buildbudy

  docker-status:
    image: lahmanja/docker-status
    container_name: docker-status
    restart: unless-stopped
    expose:
      - 9090
    volumes:
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    expose:
      - 8096
      - 8920
    volumes:
      - jellyfin_data:/config
      - ~/media:/media
    environment:
      - TZ=America/Los_Angeles

  pihole:
    image: pihole/pihole
    restart: unless-stopped
    container_name: pihole
    expose:
      - 80
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'US/Pacific'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - SYS_NICE
      - SYS_TIME

  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    environment:
      REGISTRY_HTTP_HEADERS_X_CONTENT_TYPE_OPTIONS: nosniff
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    expose:
      - 5000
    volumes:
      - registry_data:/var/lib/registry
      - ./auth:/auth

  proxpi:
    image: epicwink/proxpi
    container_name: proxpi
    restart: unless-stopped
    environment:
      PROXPI_CACHE_DIR: /var/cache/proxpi
    expose:
      - 5000
    volumes:
      - proxpi_data:/var/cache/proxpi

  pacoloco:
    image: ghcr.io/anatol/pacoloco
    container_name: pacoloco
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
    expose:
      - 9129
    volumes:
      - pacoloco_data:/var/cache/pacoloco
      - ./pacoloco/pacoloco.yaml:/etc/pacoloco.yaml

  glances:
    image: nicolargo/glances
    container_name: glances
    restart: unless-stopped
    expose:
      - 61208
    environment:
      - GLANCES_OPT=-w
    volumes:
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    pid: "host"

volumes:
  registry_data:
  buildbuddy_data:
  jellyfin_data:
  proxpi_data:
  pacoloco_data:
