repos:
  # Module-scoped Go checks, run from this directory.
  - repo: https://github.com/jmelahman/go-pre-commit-hooks
    rev: 4148d5ef186eb979ccf07d9052101b312b0f025c  # frozen: v1.1.0
    hooks:
      - id: go-mod-tidy
      - id: go-vet
      - id: go-test
      - id: go-get
