tasks:
  - bazel_test_matrix:
      universe:
        - //...
      filter_query: "kind(cc_test, tests({UNIVERSE}))"
      tag_filters:
        - -noasan
      config_matrix:
        - asan
        - tsan
        - msan
  - bazel_build_matrix:
      universe:
        - //...
      options:
        - --config=mypy
  - bazel_build_matrix:
      universe:
        - //...
      options:
        - --config=mypy
      tag_filters:
        - manual
