tasks:
  # - bazel_run_matrix:
  #     commands:
  #       - //:buildifier.check
  #       - //tools/format -- --check
  - bazel_build_matrix:
      universes:
        - //...
      options:
        - --config=mypy
  - bazel_test_matrix:
      universes:
        - //...
      filter_query: "tests({UNIVERSE})"
  - bazel_test_matrix:
      universes:
        - //...
      filter_query: "kind(cc_test, tests({UNIVERSE}))"
      configs:
        - asan
        - tsan
        - msan
      adjustments:
        - config: asan
          tag_filters:
            - -noasan
        - config: msan
          tag_filters:
            - -nomsan
        - config: tsan
          tag_filters:
            - -notsan
        - config: ubsan
          tag_filters:
            - -noubsan
