version: '3.3'

services:
  buildkite:
    image: lahmanja/buildkite:latest
    deploy:
      replicas: 3
    restart: unless-stopped
    volumes:
      - "/home/jamison/.ssh/:/root/.ssh/:rw"
      - "./buildkite-agent.cfg:/buildkite/buildkite-agent.cfg:ro"
      - "./hooks/:/buildkite/hooks/:ro"
    command: ['start', '--token', '<REDACTED>']
