apiVersion: v1
kind: ConfigMap
metadata:
  name: navidrome-config
data:
  navidrome.toml: |
    # optional config
    MusicFolder = "/music"
    DataFolder = "/config"
    Address = "0.0.0.0"
    Port = 4533
