#!/usr/bin/env bash
set -eo pipefail

shopt -s globstar

DIR="$(cd -- "$(dirname -- "$0")" && pwd)"
SITE_URL="https://jamison.lahman.dev"
BLOG_DIR="blog"

pushd "$DIR" >/dev/null || exit

# Compile HTML
for md in **/*.md; do
	if [ "$md" == "README.md" ]; then
		continue
	fi
	pandoc \
		"$md" \
		-o "${md%.md}.html" \
		--template=template.html
done

pandoc \
	feed/index.html.body \
	-o feed/index.html \
	--template=template.html \
	--from markdown+raw_html \
	--metadata=script=/scripts/feed.js \
	--metadata=title-prefix=Feed \
	--metadata=nav_feed=true

# Minify CSS
docker run --rm -i node:alpine \
	sh -c "npm install -g clean-css-cli > /dev/null && cleancss -o /dev/stdout" \
	<css/stylesheet.css >css/stylesheet.min.css

# Start RSS feed
RSS_PATH="rss.xml"
{
cat <<EOF
<?xml version="1.0"?>
<rss version="2.0">
<channel>
  <title>jmelahman's blog</title>
  <link>$SITE_URL</link>
  <description>My personal site</description>
  <language>en-us</language>
  <lastBuildDate>$(date -R)</lastBuildDate>
EOF

for md in "$BLOG_DIR"/*.md; do
    filename=$(basename "$md" .md)
    [ "$filename" = "index" ] && continue

    title=$(sed -n 's/^#\s[ ]*//p' "$md")
    date=$(sed -n 's/^date:[ ]*//p' "$md")
    pubDate=$(date -R -d "$date")

    cat <<EOF
  <item>
    <title>$title</title>
    <link>$SITE_URL/$BLOG_DIR/$filename.html</link>
    <guid>$SITE_URL/$BLOG_DIR/$filename.html</guid>
    <pubDate>$pubDate</pubDate>
  </item>
EOF
done

cat <<EOF
</channel>
</rss>
EOF
} >"$RSS_PATH"

popd >/dev/null || exit
