load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = [
    "//pybazel:__subpackages__",
    "//subtrees/pybazel/tests:__subpackages__",
])

py_library(
    name = "info",
    srcs = ["info.py"],
)

py_library(
    name = "label",
    srcs = ["label.py"],
)
