worker_processes auto;

events { }

http {
  server {
    listen 80;
    server_name cache.pacman.home;

    location / {
      proxy_pass http://pacoloco:9129;
      include includes/proxy_defaults.conf;
    }
  }

  server {
    listen 80;
    server_name shelf.home;

    location / {
      proxy_pass http://audiobookshelf;
      include includes/proxy_defaults.conf;
    }
  }

  server {
    listen 80;
    server_name video.home;

    location / {
      proxy_pass http://jellyfin:8096;
      include includes/proxy_defaults.conf;
    }
  }
}
