#!/usr/bin/env bash

set -euo pipefail

if [ -d "$BUILDKITE_BUILD_CHECKOUT_PATH" ]; then
  cd "$BUILDKITE_BUILD_CHECKOUT_PATH"
  if git config --local --get core.hooksPath; then
    git config --local --unset core.hooksPath
  fi
fi
