version: '3'

services:
  status:
    image: status:latest
    restart: unless-stopped
    ports:
      - 5000:5000
    volumes:
      - /home/jamison/.ssh/:/root/.ssh/:ro
      - ./status/database.db:/app/database.db
  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:arm64v8-latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

# Not worth with BuildBuddy.
#  bazel-remote:
#    image: quay.io/bazel-remote/bazel-remote:latest
#    user: 1001:1001
#    volumes:
#      - /var/cache/bazel-remote/:/data/:rw
#    ports:
#      - 9001:8080
#      - 9092:9092

# Doesn't work on arm.
# buildbuddy:
#    image: gcr.io/flame-public/buildbuddy-app-onprem:latest
#    restart: unless-stopped
#    ports:
#      - 1985:1985
#      - 8080:8080
