services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf
    container_name: audiobookshelf
    expose:
      - 80
    volumes:
      - ./config:/config
      - ./metadata:/metadata
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
      - 4443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  nginx-home:
    image: nginx
    container_name: nginx-home
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx-home/:/etc/nginx/:ro
    depends_on:
      - audiobookshelf
      - buildbuddy
      - docker-status
      - n8n
      - pihole
      - proxpi
      - glances

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  buildbuddy:
    image: gcr.io/flame-public/buildbuddy-app-onprem
    container_name: buildbuddy
    restart: unless-stopped
    expose:
      - 1985
      - 8080
    ports:
      - "1985:1985"
    volumes:
      - buildbuddy_data:/var/lib/buildbudy

  docker-status:
    image: lahmanja/docker-status
    container_name: docker-status
    restart: unless-stopped
    expose:
      - 9090
    volumes:
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock

  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    container_name: n8n
    environment:
      EXTERNAL_FRONTEND_HOOKS_URLS: ""
      N8N_DIAGNOSTICS_CONFIG_FRONTEND: ""
      N8N_DIAGNOSTICS_CONFIG_BACKEND: ""
      N8N_DIAGNOSTICS_ENABLED: false
      N8N_SECURE_COOKIE: false
      N8N_TEMPLATES_ENABLED: false
      N8N_VERSION_NOTIFICATIONS_ENABLED: false
    expose:
      - 5678
    volumes:
      - n8n_data:/home/node/.n8n

  pihole:
    image: pihole/pihole
    restart: unless-stopped
    container_name: pihole
    expose:
      - 80
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'US/Pacific'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - SYS_NICE

  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    environment:
      REGISTRY_HTTP_HEADERS_X_CONTENT_TYPE_OPTIONS: nosniff
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    expose:
      - 5000
    volumes:
      - registry_data:/var/lib/registry
      - ./auth:/auth

  proxpi:
    image: epicwink/proxpi
    container_name: proxpi
    restart: unless-stopped
    environment:
      PROXPI_CACHE_DIR: /var/cache/proxpi
    expose:
      - 5000
    volumes:
      - proxpi_data:/var/cache/proxpi

  ollama:
    image: ollama/ollama
    restart: unless-stopped
    container_name: ollama
    environment:
      OLLAMA_CONTEXT_LENGTH: 131072
    expose:
      - 11434
    volumes:
      - ollama_data:/root/.ollama

  glances:
    image: nicolargo/glances
    container_name: glances
    restart: unless-stopped
    expose:
      - 61208
    environment:
      - GLANCES_OPT=-w
    volumes:
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    pid: "host"

volumes:
  registry_data:
  buildbuddy_data:
  n8n_data:
  ollama_data:
  proxpi_data:
