services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    ports:
      - "13378:80"
    volumes:
      - ./config:/config
      - ./metadata:/metadata
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
      - 4443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  buildbuddy:
    image: gcr.io/flame-public/buildbuddy-app-onprem:latest
    container_name: buildbuddy
    restart: unless-stopped
    ports:
      - 1985:1985
      - 8080:8080
    volumes:
      - buildbuddy_data:/var/lib/buildbudy

  n8n:
    image: n8nio/n8n
    restart: unless-stopped
    container_name: n8n
    environment:
      EXTERNAL_FRONTEND_HOOKS_URLS: ""
      N8N_DIAGNOSTICS_CONFIG_FRONTEND: ""
      N8N_DIAGNOSTICS_CONFIG_BACKEND: ""
      N8N_DIAGNOSTICS_ENABLED: false
      N8N_SECURE_COOKIE: false
      N8N_TEMPLATES_ENABLED: false
      N8N_VERSION_NOTIFICATIONS_ENABLED: false
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

  pihole:
    image: pihole/pihole:latest
    restart: unless-stopped
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:80/tcp"
    environment:
      TZ: 'America/Los_Angeles'
      FTLCONF_dns_listeningMode: 'all'
    volumes:
      - './etc-pihole:/etc/pihole'
    cap_add:
      - SYS_NICE

  registry:
    image: registry:2
    container_name: registry
    restart: unless-stopped
    environment:
      REGISTRY_HTTP_HEADERS_X_CONTENT_TYPE_OPTIONS: nosniff
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    ports:
      - 5000:5000
    volumes:
      - registry_data:/var/lib/registry
      - ./auth:/auth

  proxpi:
    image: epicwink/proxpi
    container_name: proxpi
    restart: unless-stopped
    environment:
      PROXPI_CACHE_DIR: /var/cache/proxpi
    ports:
      - 5001:5000
    volumes:
      - proxpi_data:/var/cache/proxpi

  ollama:
    image: ollama/ollama
    restart: unless-stopped
    container_name: ollama
    environment:
      OLLAMA_CONTEXT_LENGTH: 8192
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    restart: unless-stopped
    ports:
      - "61208:61208"
    environment:
      - GLANCES_OPT=-w
    volumes:
      - ${XDG_RUNTIME_DIR}/docker.sock:/var/run/docker.sock:ro
      - /etc/os-release:/etc/os-release:ro
    pid: "host"

volumes:
  registry_data:
  buildbuddy_data:
  n8n_data:
  ollama_data:
  proxpi_data:

