import { readFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import { describe, expect, it } from "vitest"
import { LANGS } from "../src/ui/lang/types"

// These lists are generated by tools/gen-wordlists.ts and committed. The engine
// treats them as a contract, since word selection indexes into answers and
// guess validation is a lookup in allowed, so the invariants are worth pinning even
// though no code here produced them.

const WORDS = join(dirname(fileURLToPath(import.meta.url)), "..", "public", "words")
const read = (name: string) => readFileSync(join(WORDS, name), "utf8")
const parse = (name: string) => read(name).split("\n").filter(Boolean)

/**
 * The four lists, and the four numbers that are not the same in each.
 *
 * `answers` is exact because the generator takes exactly that many; `allowed` is
 * a floor because it is however many words the dictionary had, and the floors
 * are set a few hundred below what is committed so that upstream drifting a
 * little does not fail the build while upstream collapsing does.
 *
 * English is the outlier twice over and both times for the same reason: it is
 * analytic and thick with short words, so `dwyl/english-words` alone yields
 * 15,949 five-letter forms where an expanded German hunspell dictionary yields
 * 4,344. That is what sets the answer counts apart too — see ANSWER_COUNTS in
 * the generator for why the other three stop at 2,000 rather than 2,300.
 *
 * `plurals` and `witness` are the two halves of the S-final check below: words
 * that must be guessable and never the answer, and a word that must be an answer
 * despite ending in S. The witnesses are chosen to be load-bearing rather than
 * decorative — WEISS and GROSS only exist because ß folds to SS.
 */
const LANGUAGES = [
  {
    lang: "en",
    answers: 2300,
    allowed: 15_000,
    // A corpus of ordinary English is about a quarter plural by these ranks, and
    // 620 of these 2300 ended in S before the filter existed.
    sFinal: 0.05,
    plurals: ["zones", "banks", "cakes", "words", "girls", "boxes", "tries"],
    witness: "grass",
  },
  {
    lang: "es",
    answers: 2000,
    allowed: 10_000,
    sFinal: 0.05,
    plurals: ["casas", "manos", "ideas", "horas", "gafas"],
    witness: "lejos",
  },
  {
    lang: "fr",
    answers: 2000,
    allowed: 9_000,
    // The loosest of the four, at a measured 4.3%. French inflects the second
    // person singular with an S (TU CROIS, TU VIENS) and no lemma rule can see
    // that, because the lemma is the infinitive and looks nothing like it.
    sFinal: 0.06,
    plurals: ["chats", "jours", "mains", "bleus", "amies"],
    witness: "temps",
  },
  {
    lang: "de",
    answers: 2000,
    allowed: 6_000,
    sFinal: 0.05,
    plurals: ["autos", "fotos"],
    witness: "weiss",
  },
] as const

describe.each(LANGUAGES)("$lang", (language) => {
  const answers = parse(`${language.lang}/answers.txt`)
  const allowed = parse(`${language.lang}/allowed.txt`)

  describe.each([
    ["answers", answers],
    ["allowed", allowed],
  ])("%s.txt", (name, words) => {
    it("contains only lowercase five-letter words", () => {
      // Which is also the accent check. Every source but the English one is full
      // of É and Ñ and ß, and a single unfolded word would land here rather than
      // on a board that cannot draw it.
      expect(words.filter((w) => !/^[a-z]{5}$/.test(w))).toEqual([])
    })

    it("has no duplicates", () => {
      expect(words.length).toBe(new Set(words).size)
    })

    it("is sorted, so regenerating produces a readable diff", () => {
      expect(words).toEqual([...words].sort())
    })

    it("ends with a newline", () => {
      expect(read(`${language.lang}/${name}.txt`).endsWith("\n")).toBe(true)
    })
  })

  describe("the two lists together", () => {
    it("keeps every answer guessable", () => {
      const guessable = new Set(allowed)
      expect(answers.filter((w) => !guessable.has(w))).toEqual([])
    })

    // Guarding the count, not just non-emptiness: a generator bug that silently
    // truncates the corpus would still satisfy every check above.
    it("is large enough to draw a run from", () => {
      expect(answers.length).toBe(language.answers)
      expect(allowed.length).toBeGreaterThan(language.allowed)
    })

    /*
     * Wordle bars plural answers, and the reason is mechanical rather than
     * literary: a plural answer makes the last slot a free S, which turns a
     * five-letter deduction into a four-letter one. In this game it would also
     * hand S a guaranteed position, which is a scoring problem as well as a
     * deduction one: every letter here can be bought an etching and a modifier.
     *
     * Guessing one stays legal. BANKS is a fine probe; it is just never the word.
     */
    it("never makes a plural the secret word", () => {
      const secret = new Set(answers)
      for (const word of language.plurals) {
        expect(secret.has(word), word).toBe(false)
        expect(allowed.includes(word), word).toBe(true)
      }
    })

    /*
     * The catch-all behind that spot check. The generator judges "plural" against
     * a lemma set this test cannot see, so it asserts the consequence instead.
     * What is left is the words that merely happen to end in S: GRASS, FOCUS,
     * CHAOS, and — in German, where ß folds to SS — WEISS and GROSS.
     */
    it("keeps S off the end of almost every answer", () => {
      const sFinal = answers.filter((word) => word.endsWith("s"))
      expect(sFinal.length / answers.length).toBeLessThan(language.sFinal)
      expect(sFinal).toContain(language.witness)
    })
  })
})

/**
 * That the table above has a row per language, which is the one thing a
 * `describe.each` cannot check for itself: it would pass just as happily with
 * three rows as with four.
 *
 * Asserted against the setting rather than against a literal, so it is the
 * *picker* that this is pinned to. Offering a language the game cannot deal a
 * word in is the worst shape this change could take — a player chooses it, the
 * fetch 404s, and the only symptom is a title screen that will not start a run.
 */
it("ships a list for every language the game offers", () => {
  expect([...LANGS].sort()).toEqual(LANGUAGES.map((entry) => entry.lang).sort())
})
