// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so", os.Args, []testing.Test{
		{Name: "TestValidLinks", F: TestValidLinks},
		{Name: "TestBrokenLink", F: TestBrokenLink},
		{Name: "TestRecursiveBrokenLink", F: TestRecursiveBrokenLink},
		{Name: "TestDirectoryLink", F: TestDirectoryLink},
		{Name: "TestNonSymlinkArgs", F: TestNonSymlinkArgs},
		{Name: "TestHidden", F: TestHidden},
		{Name: "TestHiddenDirectory", F: TestHiddenDirectory},
		{Name: "TestMultipleRoots", F: TestMultipleRoots},
		{Name: "TestIgnoreFile", F: TestIgnoreFile},
		{Name: "TestIgnoreFileInConfigDir", F: TestIgnoreFileInConfigDir},
		{Name: "TestSingleThreaded", F: TestSingleThreaded},
		{Name: "TestUnknownFlag", F: TestUnknownFlag},
		{Name: "TestVersion", F: TestVersion},
	})
}
