name: buildprint
summary: Provides a blueprint print a buildkite pipeline.
description: |
    Provides a blueprint print a buildkite pipeline.
version: git
grade: stable
confinement: devmode
base: core20
architectures:
  - build-on: [amd64]

apps:
  buildprint:
    command: bin/buildprint
    plugs: [home, network, network-bind, removable-media]

parts:
  buildprint:
    plugin: python
    python-version: python3
    source: https://github.com/jmelahman/buildprint.git
    python-packages:
      - click==8.1.3
      - colorama==0.4.5
      - gitpython==3.1.31
      - pyyaml==6.0
      - pybazel==0.5.1
      - pip
      - setuptools
      - wheel
      - mypy==1.0.0
      - types-colorama==0.4.15.4
      - types-click==7.1.8
      - types-PyYAML==6.0.12.2
