package server

import (
	"context"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/spf13/cobra"
)

// hookMarker identifies hooks we generated, so install-hook never clobbers a
// hand-written one.
const hookMarker = "# generated by local-preview (preview install-hook)"

const hookScript = `#!/bin/sh
` + hookMarker + `
preview deploy "$(git rev-parse HEAD)" --no-wait >/dev/null 2>&1 || true
`

// preCommitRepoURL is the repository whose .pre-commit-hooks.yaml publishes
// the deploy hook (id: local-preview-deploy).
const preCommitRepoURL = "https://github.com/jmelahman/local-preview"

// releaseTagRE matches a clean release version — no distance/sha/dirty
// suffix from `git describe`, no goreleaser snapshot marker.
var releaseTagRE = regexp.MustCompile(`^v?\d+\.\d+\.\d+$`)

// releaseTag maps the binary's build version to the git tag that produced
// it (goreleaser strips the leading v), or "" for dev builds, which have no
// tag to pin.
func releaseTag(buildVersion string) string {
	if !releaseTagRE.MatchString(buildVersion) {
		return ""
	}
	return "v" + strings.TrimPrefix(buildVersion, "v")
}

// preCommitStanza is printed (never auto-applied — silently mutating a file
// the pre-commit framework re-parses is riskier than asking the user to
// paste) when the target repo already uses the pre-commit framework. It
// subscribes to the hook published in this repo's .pre-commit-hooks.yaml
// rather than inlining a local hook, so the framework builds the CLI itself
// at the pinned rev. Any release with this code also carries the manifest,
// so the binary's own release is always a valid rev to pre-fill.
func preCommitStanza(buildVersion string) string {
	rev := "vX.Y.Z  # replace with a release tag; `pre-commit autoupdate` picks the newest"
	if tag := releaseTag(buildVersion); tag != "" {
		rev = tag + "  # this CLI's release; bump with `pre-commit autoupdate`"
	}
	return "  - repo: " + preCommitRepoURL + "\n" +
		"    rev: " + rev + "\n" +
		"    hooks:\n" +
		"      - id: local-preview-deploy\n"
}

func installHookCmd() *cobra.Command {
	var dryRun bool
	cmd := &cobra.Command{
		Use:   "install-hook",
		Short: "Install a post-commit hook that deploys every commit",
		Long: "Run from inside a target repository's working tree. Installs a git\n" +
			"post-commit hook that requests a preview deploy of each new commit.\n" +
			"If the repo uses the pre-commit framework, a .pre-commit-config.yaml\n" +
			"stanza subscribing to the published hook is printed instead.",
		RunE: func(cmd *cobra.Command, args []string) error {
			return runInstallHook(cmd.Context(), cmd.OutOrStdout(), dryRun)
		},
	}
	cmd.Flags().BoolVar(&dryRun, "dry-run", false, "Print what would be written without writing it")
	return cmd
}

func runInstallHook(ctx context.Context, out io.Writer, dryRun bool) error {
	top, err := findWorktreeRoot(".")
	if err != nil {
		return fmt.Errorf("not inside a git working tree: %w", err)
	}

	if _, err := os.Stat(filepath.Join(top, ".pre-commit-config.yaml")); err == nil {
		fmt.Fprintf(out, "This repo uses the pre-commit framework — subscribe to the published hook by\n")
		fmt.Fprintf(out, "adding this to .pre-commit-config.yaml (the framework builds the CLI itself\n")
		fmt.Fprintf(out, "at the pinned rev, so nothing needs to be preinstalled):\n\n")
		fmt.Fprint(out, preCommitStanza(Build().Version))
		fmt.Fprintf(out, "\nThen install the post-commit stage: `pre-commit install --hook-type post-commit`\n")
		fmt.Fprintf(out, "(prek: `prek install --hook-type post-commit`).\n")
		return nil
	}

	gitDir, err := localGitDir(top)
	if err != nil {
		return err
	}
	hookPath := filepath.Join(gitDir, "hooks", "post-commit")

	if existing, err := os.ReadFile(hookPath); err == nil && !strings.Contains(string(existing), hookMarker) {
		return fmt.Errorf("%s already exists and wasn't generated by local-preview — add this line to it yourself:\n  preview deploy \"$(git rev-parse HEAD)\" --no-wait || true", hookPath)
	}

	if dryRun {
		fmt.Fprintf(out, "would write %s:\n\n%s", hookPath, hookScript)
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(hookPath), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(hookPath, []byte(hookScript), 0o755); err != nil {
		return err
	}
	fmt.Fprintf(out, "installed %s — every commit now deploys a preview\n", hookPath)
	return nil
}
