default_install_hook_types:
  - pre-push
repos:
  # See https://prek.j178.dev/builtin/?h=built#2-explicit-builtin-repository
  - repo: builtin
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
  - repo: https://github.com/jmelahman/tag
    rev: 05c7b0f4da54388f7d31fe43f2ebe8458bbff3f5  # frozen: v0.6.1
    hooks:
      - id: tag-check
