[package]
name = "release-tag"
version = "0.6.0"
edition = "2021"
rust-version = "1.82"
description = "Automatically create semantic version git tags"
authors = ["Jamison Lahman <jamison@lahman.dev>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/jmelahman/tag"
keywords = ["git", "release", "releasing", "semver", "tagging"]
categories = ["command-line-utilities", "development-tools"]

[[bin]]
name = "tag"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = {
  version = "4",
  default-features = false,
  features = ["derive", "error-context", "help", "std", "usage"]
}
clap_complete = "4"
log = "0.4"

[profile.release]
opt-level = "z"
strip = true
lto = true
panic = "abort"
codegen-units = 1
