// Code generated by "so test". DO NOT EDIT.

package main

import (
	"solod.dev/so/os"
	"solod.dev/so/testing"
)

func main() {
	testing.RunTests("so", os.Args, []testing.Test{
		{Name: "TestConfIgnore", F: TestConfIgnore},
		{Name: "TestConfNegateAndGlob", F: TestConfNegateAndGlob},
		{Name: "TestUserConfAndRepoOverride", F: TestUserConfAndRepoOverride},
		{Name: "TestConfFileNeverLinked", F: TestConfFileNeverLinked},
		{Name: "TestForceGuarded", F: TestForceGuarded},
		{Name: "TestCIConfigsSkippedByDefault", F: TestCIConfigsSkippedByDefault},
		{Name: "TestLinkNoConfigDir", F: TestLinkNoConfigDir},
		{Name: "TestLinkCreatesAndRepairsLinks", F: TestLinkCreatesAndRepairsLinks},
		{Name: "TestLinkConflict", F: TestLinkConflict},
		{Name: "TestNotARepo", F: TestNotARepo},
		{Name: "TestPreCommitInsertExisting", F: TestPreCommitInsertExisting},
		{Name: "TestMigrateBasic", F: TestMigrateBasic},
		{Name: "TestMigrateIdempotent", F: TestMigrateIdempotent},
		{Name: "TestMigrateExplicit", F: TestMigrateExplicit},
		{Name: "TestMigrateSkipsDefaults", F: TestMigrateSkipsDefaults},
		{Name: "TestMigrateDryRun", F: TestMigrateDryRun},
		{Name: "TestGitignoreCompanionPatterns", F: TestGitignoreCompanionPatterns},
		{Name: "TestMigrateConflict", F: TestMigrateConflict},
		{Name: "TestNolinkSkipsAndCleansUp", F: TestNolinkSkipsAndCleansUp},
		{Name: "TestNolinkMigrate", F: TestNolinkMigrate},
		{Name: "TestNolinkUserLevelRejected", F: TestNolinkUserLevelRejected},
	})
}
