repos:
  # Module-scoped Go checks, run from this directory.
  - repo: https://github.com/jmelahman/go-pre-commit-hooks
    rev: 51820c603eaa31a81da2ff40ccb83ca2be1dd9d2  # frozen: v1.2.0
    hooks:
      - id: go-mod-tidy
      - id: go-vet
      - id: go-test
      - id: go-get
