package pkgbuild

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

// TestParseSrcInfo pins the inert key-value parsing of .SRCINFO: pkgbase and
// pkgname sections are merged, repeated keys accumulate in order.
func TestParseSrcInfo(t *testing.T) {
	si := ParseSrcInfo([]byte(`# generated by makepkg

pkgbase = demo
	pkgdesc = A demo
	pkgver = 1.0.0
	arch = x86_64
	depends = glibc
	depends = zlib
	source = https://example.com/demo.tar.gz
	no_equals_sign_here

pkgname = demo
`))

	if got, ok := si.Get("pkgbase"); !ok || got != "demo" {
		t.Errorf("Get(pkgbase) = (%q, %v), want (demo, true)", got, ok)
	}
	if got, ok := si.Get("pkgver"); !ok || got != "1.0.0" {
		t.Errorf("Get(pkgver) = (%q, %v), want (1.0.0, true)", got, ok)
	}
	if got := si.All("depends"); !reflect.DeepEqual(got, []string{"glibc", "zlib"}) {
		t.Errorf("All(depends) = %v, want [glibc zlib]", got)
	}
	if got, ok := si.Get("depends"); !ok || got != "glibc" {
		t.Errorf("Get(depends) = (%q, %v), want the first value (glibc, true)", got, ok)
	}
	// Comments, blank lines, and lines without "=" are skipped.
	if got := si.All("no_equals_sign_here"); got != nil {
		t.Errorf("All(no_equals_sign_here) = %v, want nil", got)
	}
	if got, ok := si.Get("missing"); ok || got != "" {
		t.Errorf("Get(missing) = (%q, %v), want (\"\", false)", got, ok)
	}
	if got := si.All("missing"); got != nil {
		t.Errorf("All(missing) = %v, want nil", got)
	}
}

// TestLoadSrcInfo pins that a .SRCINFO next to the PKGBUILD is picked up, and
// that install scriptlets it declares are loaded too.
func TestLoadSrcInfo(t *testing.T) {
	dir := t.TempDir()
	files := map[string]string{
		"PKGBUILD":     "pkgname=demo\npkgver=1.0.0\n",
		".SRCINFO":     "pkgbase = demo\n\tpkgver = 1.0.0\n\tinstall = demo.install\n",
		"demo.install": "post_install() {\n  echo hi\n}\n",
	}
	for name, content := range files {
		if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	pkg, err := Load(dir)
	if err != nil {
		t.Fatalf("load: %v", err)
	}
	if pkg.SrcInfo == nil {
		t.Fatal("SrcInfo is nil, want it parsed from .SRCINFO")
	}
	if got, ok := pkg.SrcInfo.Get("pkgver"); !ok || got != "1.0.0" {
		t.Errorf("SrcInfo.Get(pkgver) = (%q, %v), want (1.0.0, true)", got, ok)
	}
	if len(pkg.Scriptlets) != 1 || filepath.Base(pkg.Scriptlets[0].Path) != "demo.install" {
		t.Errorf("Scriptlets = %+v, want demo.install from the .SRCINFO install field", pkg.Scriptlets)
	}
}

// TestLoadNoSrcInfo pins that a missing .SRCINFO is not an error.
func TestLoadNoSrcInfo(t *testing.T) {
	pkg := loadPKGBUILD(t, "pkgname=demo\npkgver=1.0.0\n")
	if pkg.SrcInfo != nil {
		t.Errorf("SrcInfo = %+v, want nil when no .SRCINFO exists", pkg.SrcInfo)
	}
	if len(pkg.Scriptlets) != 0 {
		t.Errorf("Scriptlets = %+v, want none", pkg.Scriptlets)
	}
}
