name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bazelbuild/setup-bazelisk@v1
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: bazel run //:buildifier_check
      - run: bazel run //tools/format -- --check
      - run: bazel build //...
      - run: bazel test //...
