name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel run //:buildifier.check
      - run: bazel build //...
      - name: Install deps
        run: >-
          python -m pip install --upgrade pip &&
          pip install -r third_party/requirements.txt
      - run: ruff format .
      - run: ruff check .
      - run: mypy .
      # - run: bazel test //...
      - run: bazel test --config asan $(bazel query 'kind("cc_test", //...)')
      # # TODO: https://github.com/google/sanitizers/wiki/MemorySanitizerLibcxxHowTo
      # # - run: bazel test --config msan $(bazel query 'kind("cc_test", //...)')
      - run: bazel test --config tsan $(bazel query 'kind("cc_test", //...)')
      - run: bazel test --config ubsan $(bazel query 'kind("cc_test", //...)')
      - run: >-
          docker run --tmpfs /run --tmpfs /run/lock --tmpfs /tmp -v
          /var/cache/snapd:/var/cache/snapd/ -v /run/snapd.socket:/run/snapd.socket
          lahmanja/snapify:v1.0.1 snapify --noninteractive
