name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: bazelbuild/setup-bazelisk@v1
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel
      - run: bazel run //:buildifier.check
      - run: bazel run //tools/format -- --check
      - run: bazel build --config mypy //...
      - run: bazel test //...
      - run: docker run --tmpfs /run --tmpfs /run/lock --tmpfs /tmp -v
        /var/cache/snapd:/var/cache/snapd/ -v /run/snapd.socket:/run/snapd.socket lahmanja/snapify:v1.0.0 python -m snapify --noninteractive
