load("@rules_python//python:defs.bzl", "py_binary", "py_library")

py_binary(
    name = "correct",
    srcs = ["correct.py"],
    tags = ["manual"],
)

py_library(
    name = "correct_lib",
    srcs = ["correct.py"],
    tags = ["manual"],
)

py_binary(
    name = "incorrect",
    srcs = ["incorrect.py"],
    tags = ["manual"],
)

py_library(
    name = "incorrect_lib",
    srcs = ["incorrect.py"],
    tags = ["manual"],
)
